Lecture1 button
js-tasks-ru/htmlcss-20240614_nkim18717 pull request #4
Opened 2024-06-25 19:07 UTC by natalya87324

2024-06-25 19:08 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-06-29 04:55 UTC, GSemikozov requested changes

2024-06-29 04:55 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  width: 189px;
ширину не фиксируем, а вот высоту - наоборот, будет полезно

2024-06-29 04:55 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  padding: 15px 0;
по краям тоже надо `15 15 14`

2024-06-29 04:55 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  color: var(--white);
не хватает стилей для оформления текста: font-family, line-height, font-weight, font-size

2024-06-29 04:55 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.btn_primary_disabled {
у нас будет общий для всех типов - .btn:disabled, фон менять не надо

2024-06-29 13:46 UTC, natalya87324 commented
Привет) Внесла исправления по замечаниям. Немного не уверена, что правильно поняла как сделать для disabled состояния кнопки.

2024-07-03 13:52 UTC, GSemikozov requested changes

2024-07-03 13:52 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.btn_alternate:hover {
в этом состоянии меняем только border-color

2024-07-03 13:52 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.btn_disabled {
.btn:disabled

2024-07-03 13:52 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  cursor: default;
pointer-events: none

2024-07-03 13:52 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +        <button class="btn btn_disabled">Primary disabled</button>
`<button class="btn btn_primary" disabled>`

2024-07-05 11:36 UTC, natalya87324 commented
Привет! поправила, вроде все должно быть ок теперь... спасибо за подсказки)

2024-07-05 12:54 UTC, GSemikozov approved these changes

2024-07-05 12:55 UTC, merged