Lecture 1 accordeon component solution
js-tasks-ru/htmlcss-20240614_nkim18717 pull request #5
Opened 2024-06-27 16:10 UTC by natalya87324

2024-06-27 16:10 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-06-27 16:23 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-06-29 04:57 UTC, GSemikozov requested changes

2024-06-29 04:57 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap');
шрифты подключаем в fonts.css

2024-06-29 04:57 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +body {
глобальные стили в файлах стилей компонентов ни в коем случае не описываем, это не нужно)

2024-06-29 04:57 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.container {
вспомогательные стили для отображения компонента?

2024-06-29 04:57 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  width: 100%;
лишнее (блочный же)

2024-06-29 04:57 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  line-height: 24px;
не хватает стилей для оформления текста

2024-06-29 04:57 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item {
.accordion__item[open] - паддинг снизу 32

2024-06-29 04:57 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  line-height: 24px;
и еще наверно отступ сверху до заголовка?

2024-06-29 14:15 UTC, natalya87324 commented on 03-lection1/02-accordion/accordion.css
> +.container {
Убрала, т.к. поняла, что контейнер тут пока что лишний )

2024-07-03 13:57 UTC, GSemikozov requested changes

2024-07-03 13:57 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  max-width: 730px;
лишнее

2024-07-05 11:55 UTC, natalya87324 commented on 03-lection1/02-accordion/accordion.css
> +  max-width: 730px;
убрала совсем этот элемент)

2024-07-05 12:55 UTC, GSemikozov approved these changes

2024-07-05 12:55 UTC, merged