Add cards on the main page
js-tasks-ru/htmlcss-20240614_nkim18717 pull request #8
Opened 2024-07-10 16:46 UTC by natalya87324

2024-07-10 16:46 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-07-12 13:56 UTC, GSemikozov requested changes

2024-07-12 13:56 UTC, GSemikozov commented on components/main-home/main-home.css
> +.stats_preview {
если это модификатор блока .stats - то там и добавляем стили

2024-07-12 13:56 UTC, GSemikozov commented on components/main-home/main-home.css
> +.stats_preview {
но вообще - это лишнее, достаточно будет просто max-width

2024-07-13 15:39 UTC, natalya87324 commented on components/main-home/main-home.css
> +.stats_preview {
Привет! Перенесла стили модификатора блока в histogram.css. Добавила max-width. Без margin он у меня почему-то растянулся на всю ширину карточки, пришлось margin оставить. Может я не туда max-width впихнула?

2024-07-13 15:51 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-07-15 21:21 UTC, GSemikozov requested changes

2024-07-15 21:21 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  margin-bottom: 75px;
марджины на уровне блока не задаем

2024-07-15 21:21 UTC, GSemikozov commented on index.html
> +                        <div class="card">
`<a>`

2024-07-15 21:21 UTC, GSemikozov commented on index.html
> +                            <h2 class="card__title">Histogram</h2>
h5 и следует снизу, верно?

2024-07-15 21:21 UTC, GSemikozov commented on index.html
> +                            <div class='stats stats_preview'>
это надо завернуть в отдельный элемент card__preview и разруливать через него

2024-07-18 18:30 UTC, natalya87324 commented on index.html
> +                        <div class="card">
Уточнить - мне нужно в <div> вложить <a>? Если я исправлю все дивы на <a>, то в <a> же вроде нельзя вставлять блочные элементы, а компоненты у нас блочные...

2024-07-18 19:15 UTC, natalya87324 commented on index.html
> +                        <div class="card">
Если я меняю div на а, то у меня слетает верстка карточки с встроенным компонентом...Еще возник вопрос - в теории пишут. что нельзя вкладывать блочные элементы в строчные - тут получается мы можем вкладывать?

2024-07-19 15:46 UTC, GSemikozov approved these changes

2024-07-19 15:46 UTC, merged